### ISSUE TITLE
How can I test the app?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [gojibjib/jibjib#1]
Could not attend Coding da Vinci but followed it on Twitter a bit and would like to take a look at your app but could not find a way to install or otherwise test it.

**Comment by obitech** [comment]
We're currently trying to figure out a long-term concept to pay for the necessary infrastructure to support the app. We hope to release it during the next couple months, we'll keep you posted here! For now you could compile the app yourself and follow the [deploy instructions](https://github.com/gojibjib/jibjib-api/tree/master/deploy) to setup the backend.

**Comment by obitech** [comment]
Hey Daniel, the app is now available in the Google Play Store: [JibJib](https://play.google.com/store/apps/details?id=de.cdvost.jibjib)
