### ISSUE TITLE
Using this project to recognize a specific person instead a specific bird

### ISSUE THREAD

**Issue by billyjoker** [gojibjib/jibjib#10]
Hi, i was wondering if providing a sample reference sound for a specific human voice, it could be work detecting just that human voice (but not detect another voices, that would be a fake detection), in the same way that you are detecting specific singing birds.

Could you give me some steps to start working with this point? Thanks!!

**Comment by obitech** [comment]
@billyjoker so you would like to build a classifier for human voices? Say you have a data set with five different persons / voice patterns and you would like to send a voice recording to identify the person who was speaking?

**Comment by billyjoker** [comment]
@obitech you have described exactly what i would like to reach. Currently i have some large audio files (about 1h, mp3 format), and if you think this is possible, how could i start with this? Thanks!!

**Comment by sebibi07** [comment]
Hey @billyjoker , sounds like a totally doable job for the Vggish model that we used. You first should convert your files into .wav format, maybe also split them into shorter files to build an extensive data set. Your dataset then needs to be arranged in such a way that all files are located in subfolders with names that correspond to your files' classes. Pass the path to your repository as an argument in "load_spectrogram()" and you should be good to go!

**Comment by obitech** [comment]
I will close this now. Please head over to the [jibjib-model](https://github.com/gojibjib/jibjib-model) repo if you have any further questions regarding the model. Thanks!
