### ISSUE TITLE
Gradle sync failed: Could not find method buildConfigField() 

### ISSUE THREAD

**Issue by billyjoker** [gojibjib/jibjib#11]
Hi, i'm trying to compile the project, but i get this error:

Gradle sync failed: Could not find method buildConfigField() for arguments [String, Base_URL, BuildType_Decorated{name=WEBServiceBaseURL, debuggable=false, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=null, embedMicroApp=true, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}}] on BuildType_Decorated{name=debug, debuggable=true, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=SigningConfig_Decorated{name=debug, storeFile=C:\Users\grb74278\.android\debug.keystore, storePassword=android, keyAlias=AndroidDebugKey, keyPassword=android, storeType=C:\Users\grb74278\.android\debug.keystore, v1SigningEnabled=true, v2SigningEnabled=true}, embedMicroApp=false, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType. Consult IDE log for more details (Help | Show Log) (6 s 993 ms)

**Comment by obitech** [comment]
Thanks for your comment! @pplitzner can you look into this?

**Comment by billyjoker** [comment]
I think that the WEBServiceBaseURL has no value to find:

        android.buildTypes.each { type ->
            type.buildConfigField 'String', 'Base_URL', WEBServiceBaseURL
        }

So, if i add into the gradle.properties:

`WEBServiceBaseURL = "some url"`

**EDIT:** after i added a random url to do the test, i could build the project. The project launchs, but when i start/stop recording it shows a toast: "Ooops, something went wrong, try it again"

**Comment by pplitzner** [comment]
Hey, sorry for the late reply. 
Exactly, you need to provide the service URL of the backend service to let the app communicate with it.
To provide your own backend service please have a look at https://github.com/gojibjib/jibjib-api and https://github.com/gojibjib/deploy.
The error message pops up because the backend service could not be found.

**Comment by pplitzner** [comment]
I updated the README.md accordingly.
